spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: analytics_service
    password: ${RABBIT_PASSWORD}

bot:
  token: ${BOT_TOKEN}
  name: testmarkwerthhtu_bot

rabbitmq:
  queue: telegram-notifications-queue

quota:
  url: http://rate-limiter:8080/quota/telegram-api